name: Release

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Test
        run: cargo test
      - name: Lint
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Enable the WebAssembly compilation target
        run: rustup target add wasm32-unknown-unknown
      - name: Build WebAssembly binary
        run: cargo build --target wasm32-unknown-unknown
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli
      - name: Build JavaScript glue code
        run: wasm-bindgen target/wasm32-unknown-unknown/debug/puzzle_platformer.wasm --out-dir ./pkg --target web
      - name: Prepare upload
        run: mkdir -p staging/ && cp -r index.html pkg/ staging/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./staging

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
